language: node_js
sudo: false
node_js:
- 10
addons:
  chrome: stable
install:
- npm install
- npm install codecov -g
script:
- ng test --code-coverage --watch false --browsers=ChromeHeadless
- nyc report --reporter=json > coverage/coverage.json
after_success:
- codecov
